name: cd

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/apps/echo-images
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install --omit=dev
            pm2 start pm2.config.json --env production
